version: '3.8'

services:
  db:
    image: mariadb:11.3
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: superSterkRootWachtwoord123!
      MARIADB_DATABASE: nextcloud
      MARIADB_USER: nextcloud
      MARIADB_PASSWORD: sterkWachtwoord456!
    volumes:
      - nextcloud_db:/var/lib/mysql

  app:
    image: nextcloud:29
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      MYSQL_PASSWORD: sterkWachtwoord456!
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db

volumes:
  nextcloud_db:
  nextcloud_data:
