version: '3.8'

services:
  app:
    image: nextcloud:29
    container_name: nextcloud-app
    restart: unless-stopped
    ports:
      - "1000:80"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - nextcloud_data:/var/www/html

volumes:
  nextcloud_data:
