version: '3.8'

services:
  db:
    image: mariadb:11
    container_name: nextcloud-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: supergeheim
      MARIADB_DATABASE: nextcloud
      MARIADB_USER: nextcloud
      MARIADB_PASSWORD: nextcloud123
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: nextcloud:29
    container_name: nextcloud-app
    restart: always
    ports:
      - "1000:80"
    environment:
      MYSQL_PASSWORD: nextcloud123
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
  nextcloud_data:
