version: "3.8"

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tR9$eP1!zQ7mWx@L
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: tR9$eP1!zQ7mWx@L
    volumes:
      - db:/var/lib/mysql

  app:
    image: nextcloud
    ports:
      - "8080:80"
    volumes:
      - nextcloud:/var/www/html
    environment:
      MYSQL_PASSWORD: tR9$eP1!zQ7mWx@L
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    depends_on:
      - db

volumes:
  nextcloud:
  db:
