version: '3.8'

services:
  app:
    image: nextcloud:29
    container_name: nextcloud-app
    restart: always
    ports:
      - "1000:80"
    volumes:
      - nextcloud_data:/var/www/html

volumes:
  nextcloud_data:
