version: '3.9'

services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: examplepassword
      MARIADB_DATABASE: nextcloud
      MARIADB_USER: nextcloud
      MARIADB_PASSWORD: nextcloudpassword
    volumes:
      - nextcloud_db:/var/lib/mysql

  app:
    image: nextcloud
    restart: always
    ports:
      - "1000:80"   # poort 1000 op je server → poort 80 in container
    environment:
      MYSQL_PASSWORD: nextcloudpassword
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db

volumes:
  nextcloud_data:
  nextcloud_db:

